trigger:
  batch: true
  branches:
    include:
      - "*"
  tags:
    include:
      - "*"
pr:
  branches:
    include:
      - "*"

jobs:
  - job: Build
    displayName: "Build"

    pool:
      vmImage: "ubuntu-latest"

    steps:
      - task: NodeTool@0
        displayName: "Install Node"
        inputs:
          versionSpec: "12.x"

      - task: Cache@2
        displayName: "Check Cache"
        inputs:
          key: "yarn | yarn.lock"
          path: "node_modules"
          cacheHitVar: CACHE_RESTORED

      - script: "yarn install --frozen-lockfile --non-interactive"
        displayName: "Install Node Dependencies"

      - script: "yarn build:ts"
        displayName: "Build Linux Project"

      - script: "yarn package:linux dir"
        displayName: "Pack Release"

      - task: ArchiveFiles@2
        displayName: "Archive Directory"
        inputs:
          rootFolderOrFile: "dist/linux-unpacked"
          includeRootFolder: false
          archiveType: tar
          tarCompression: gz
          archiveFile: "jellyfin-desktop.tar.gz"

      - task: PublishPipelineArtifact@1
        displayName: "Publish Artifacts"
        inputs:
          targetPath: "$(Build.SourcesDirectory)/jellyfin-desktop.tar.gz"
          artifactName: "jellyfin-desktop"

  - job: Lint
    displayName: "Lint"

    pool:
      vmImage: "ubuntu-latest"

    steps:
      - task: NodeTool@0
        displayName: "Install Node"
        inputs:
          versionSpec: "12.x"

      - task: Cache@2
        displayName: "Check Cache"
        inputs:
          key: "yarn | yarn.lock"
          path: "node_modules"
          cacheHitVar: CACHE_RESTORED

      - script: "yarn install --frozen-lockfile --non-interactive"
        displayName: "Install Dependencies"

      - script: "yarn lint"
        displayName: "Run ESLint"

  - job: Publish
    displayName: "Publish"

    dependsOn: Build
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags')

    pool:
      vmImage: "ubuntu-latest"

    steps:
      - script: 'echo "##vso[task.setvariable variable=TAG]$(git describe --tags)"'
        displayName: "Set Tag Variable"

      - task: NodeTool@0
        displayName: "Install Node"
        inputs:
          versionSpec: "12.x"

      - task: Cache@2
        displayName: "Check Cache"
        inputs:
          key: "yarn | yarn.lock"
          path: "node_modules"
          cacheHitVar: CACHE_RESTORED

      - script: "apt-get install -y rpmbuild"
        displayName: "Install Apt Dependencies"

      - script: "yarn install --frozen-lockfile --non-interactive"
        displayName: "Install Node Dependencies"

      - script: "yarn build:linux"
        displayName: "Build Linux Packages"

      - script: "mkdir jellyfin-desktop"
        displayName: "Make Output Directory"

      - script: "cp dist/*.{AppImage,tar.xz,snap,deb,rpm} jellyfin-desktop"
        displayName: "Move Binaries to Output"

      - task: PublishPipelineArtifact@1
        displayName: "Publish Artifacts"
        inputs:
          targetPath: "jellyfin-desktop"
          artifactName: "jellyfin-desktop"

      - task: GithubRelease@0
        displayName: "GitHub Upload"
        inputs:
          gitHubConnection: Jellyfin Release Download
          assets: "jellyfin-desktop"
          action: "edit"
          assetUploadMode: "replace"
          tag: "$(TAG)"
